### ISSUE TITLE
Need to define how Endorsements can appear in the Accepted Claims set

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats-wg/draft-ietf-rats-corim#158]
The RATS Architecture defines Endorsements as the entity the Verifier may  use after the 
Evidence Claims Matches the Reference Values,

The Accepted Claims Set (ACS) is a Data Structure Set containing Claims which have been marked as 
`Ready for Appraisal` 

Now if the Appraisal has not been done, how ACS contains Endorsed Values/ Endorsements needs to be clearly described when this can happen.

**Comment by nedmsmith** [comment]
If we're using the ACS definition in section 5.1: "Accepted Claims Set (ACS): A structure that holds EMT Claims that have been vetted following the appraisal process. The ACS describes the actual state of an Attester that has been vetted by Appraisal Policy. The ACS also keeps track of a Claim's authority."

Then it isn't clear that ACS contains claims that are "ready for appraisal". 

Can you cite where this text appears?

**Comment by yogeshbdeshpande** [comment]
@nedmsmith It is quite clear right at the start of section:[5.3.2. ](https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#section-5.3.2)[The Accepted Claims Set](https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-the-accepted-claims-set)

_At the end of the Evidence collection process Evidence has been converted into a format suitable for appraisal. To this end, this document describes an accepted-claims-set format and the algorithms used to compare it against CoMID Reference Values._

**Comment by nedmsmith** [comment]
> @nedmsmith It is quite clear right at the start of section:[5.3.2. ](https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#section-5.3.2)[The Accepted Claims Set](https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-the-accepted-claims-set)
> 
> _At the end of the Evidence collection process Evidence has been converted into a format suitable for appraisal. To this end, this document describes an accepted-claims-set format and the algorithms used to compare it against CoMID Reference Values._

I don't think the idea of an internal representation that is initialized (as a first appraisal stage) with Evidence claims runs counter to the idea that the initialized ACS isn't still ready for subsequent appraisal stages. 

It isn't clear if your point is that an empty / uninitialized ACS is the only time when an ACS is "ready for appraisal". A different view could be that the ACS is always ready for appraisal until appraisal has completed.

Verifier logic that accepts claims asserted under the authority of the Attester key is valid. 
Verifier logic that accepts claims asserted by a RVP as Ref Vals is valid iff there are matching Attester asserted claims. For those claims that match, an EMT is formed that contains the matching claims that are jointly asserted under the both the RVP and the Attester authority.  Any claims asserted by the Attester that didn't match Ref Vals are still valid under the authority of the Attester. These may be represented by a different EMT than those asserted by the RVP. But no claims need to be thrown away, they are just not asserted by the RVP.

Even if no RVP claims are "matched" the Verifier can produce a valid result consisting only of Attester asserted claims. This result might not be interesting to a RP (based on RP policy) but it is still a valid result.

**Comment by yogeshbdeshpande** [comment]
@nedmsmith Seems to me that I have not made my point clear to you.

My point was about Endorsements, while you seem to be pointing to Reference Values supplied by RVP.

I am more pointing to the fact that we can have a two stage population of ACS, where:

Stage 1: ACS Claims are matched against Ref Values from RVP

Stage 2: Then some Endorsements (known as Conditional Endorsements) are populated inside ACS, based on satisfying the matching criterion above.

We need to highlight Staged Evidence Matching to clarify, how Endorsements can be added to ACS, (if driven by an Appraisal Policy)

**Comment by nedmsmith** [comment]
Matching Endorsements to ACS works the same way as matching RVPs to ACS in that the claims contained in the ACS at the time the endorsements are "matched" matters. It assumes the ACS contains accepted claims that are the result of having applied all applicable RV claims already. 

The terminology "ACS is ready for appraisal" assumes this context (that is, the next stage can begin with the previous stage ACS "is ready").

Continuing on the staging discussion, processing conditional endorsements also is stage dependent. This stage is separate from the endorsements stage. There should be discussion on when the ACS is ready for appraisal of condition endorsements. I believe it should follow processing of Endorsements.

There is still a question around how to stage multiple conditional endorsement triples because it is possible to get different results if different conditional endorsements are staged differently. One possible way to constrain staging to guarantee consistency is to require the condition (in conditional endorsement) to be applied to the previous (endorsements) stage results, rather than allowing each conditional endorsement triple being applied to the ACS state following application of a previously processed conditional endorsement.

To summarize stages for a given group context:
- stage 1 : process evidence claims into ACS (under the authority of the Attester)
- stage 2 : process RVs
- stage 3 : process endorsement claims
- stage 4 : process conditional endorsements (against stage 3 state)
- stage 5 : process appraisal policies

Note: It might make sense to treat conditional endorsements and conditional series endorsements in separate stages. The motivation is to allow flexibility in allowing series endorsements to take advantage of state changes applied by conditional endorsements. My choice of staging series endorsements after stage 3 is arbitrary. It is a way to ensure consistency.

Note: There is potential for inconsistent results based on when coswid triples are processed.  The cowsid tag can contain values that this spec would describe as endorsed values (or conditional endorsed values based on acceptance of the reference values contained in the coswid payload). All of the coswid content above the payload are conditionally endorsed. Options: (a)Process coswids as a separate stage. (b) define coswid as a measurement type that extends measurement-values-map (fits into existing stages). 

Revised stages for a given group context:
- stage 1 : process evidence claims into ACS (under the authority of the Attester)
- stage 2 : process RVs
- stage 3 : process endorsement claims
- stage 4 : process coswid triples (assuming option (a) above)
- stage 5 : process conditional endorsements (against stage 4 state)
- stage 6 : process conditional series endorsements (against stage 5 state)
- stage 7 : process appraisal policies

**Comment by yogeshbdeshpande** [comment]
Closing as this is no longer an issue!
