### ISSUE TITLE
Cleanup Section 5.4.3. Adding CoMID Endorsed Values to the Accepted Claims Set

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#179]
Section 5.4.3 "Adding CoMID Endorsed Values to the Accepted Claims Set" hasn't been authored yet. It seems relevant to work on this text since there is on-going work to define and refine endorsement triples.

Suggested text:
"An Endorser may publish Endorsements, which add new claims to the Accepted Claims Set (ACS) if specified conditions of the ACS are met. This section describes the process performed by the Verifier to determine if the ACS status satisfies the Endorsement condition and where to add the Endorsement claims.

The verifier compares the condition specified by endorsement triples to the ACS. Endorsement conditions may describe environments, or combinations of environment-measurement pairings, specific measurement values, and the authority that asserted the claims.

If the condition matches, the Endorsement claims, including the Endorser's authority, are added to the ACS. The new Endorsed claims are added to the part of the ACS as described by Endorsement triples (see {{sec-comid-triple-endval}}, {{sec-comid-triple-cond-series}}, {{sec-comid-triple-cond-end}}, {{sec-comid-triple-mec-endorsement}})."

**Comment by deeglaze** [comment]
I don't understand the wontfix, since I don't understand endorsed triples from the text as written.

> An Endorsed Values triple declares additional claims that are valid when a Target Environment has been verified against reference measurements.

There is no separation of the measurement-values-map contents into evidence property or endorsement property, so I'm not sure what the actual condition is that you're checking. If "A says X only if B says X about environment E", then are we supposed to track that X came from reference triples instead of endorsement triples, so that to process an endorsement "A says Y only if C says Y about environment E", we check that E had a reference triple already accepted by A (A is the CoRIM issuer)? And the properties in question are irrelevant? Are all reference triples required preconditions or is does just one need to be accepted?

I don't see similar conditions on reference values for the conditional endorsements triples, so it seems only this triple has a triple-type processing order requirement. Is the order across CoMID processing, within fixed point, or only locally to the single CoMID in a single step?

**Comment by nedmsmith** [comment]
Addressed through refactoring.
